---
name: DBIx-Class-Schema-Loader
version: 0.02999_04
author:
  - 'Brandon Black, C<blblack@gmail.com>'
abstract: Dynamic definition of a DBIx::Class::Schema
license: perl
requires:
  Class::Accessor::Fast: 0.22
  Class::C3: 0.11
  Class::Data::Accessor: 0.02
  DBIx::Class: 0.0599904
  Lingua::EN::Inflect::Number: 1.1
  Text::Balanced: 0
  UNIVERSAL::require: 0.1
recommends:
  DBD::DB2: 0.78
  DBD::Pg: 1.45
  DBD::SQLite: 1.11
  DBD::mysql: 3.0002
build_requires:
  DBD::SQLite: 1.11
  DBI: 1.5
  Test::More: 0.32
provides:
  DBIx::Class::Schema::Loader:
    file: lib/DBIx/Class/Schema/Loader.pm
    version: 0.02999_04
  DBIx::Class::Schema::Loader::Base:
    file: lib/DBIx/Class/Schema/Loader/Base.pm
  DBIx::Class::Schema::Loader::DBI:
    file: lib/DBIx/Class/Schema/Loader/DBI.pm
  DBIx::Class::Schema::Loader::DBI::DB2:
    file: lib/DBIx/Class/Schema/Loader/DBI/DB2.pm
  DBIx::Class::Schema::Loader::DBI::Pg:
    file: lib/DBIx/Class/Schema/Loader/DBI/Pg.pm
  DBIx::Class::Schema::Loader::DBI::SQLite:
    file: lib/DBIx/Class/Schema/Loader/DBI/SQLite.pm
  DBIx::Class::Schema::Loader::DBI::mysql:
    file: lib/DBIx/Class/Schema/Loader/DBI/mysql.pm
  DBIx::Class::Schema::Loader::RelBuilder:
    file: lib/DBIx/Class/Schema/Loader/RelBuilder.pm
  DBIx::Class::Schema::Loader::Writing:
    file: lib/DBIx/Class/Schema/Loader/Writing.pm
generated_by: Module::Build version 0.2612
