---
abstract: 'Dynamic definition of a DBIx::Class::Schema'
author:
  - 'blblack: Brandon Black <blblack@gmail.com>'
build_requires:
  DBD::SQLite: 1.29
  DBI: 1.56
  ExtUtils::MakeMaker: 6.42
  File::Copy: 0
  File::Path: 2.07
  File::Temp: 0.16
  IPC::Open3: 0
  Moose: 1.12
  MooseX::NonMoose: 0.15
  Test::Exception: 0
  Test::More: 0.94
  Test::Warn: 0.21
  namespace::autoclean: 0.09
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Schema-Loader
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan: 0
  Class::Accessor::Grouped: 0.09006
  Class::C3::Componentised: 1.0005
  Class::Inspector: 0
  Class::Unload: 0
  DBIx::Class: 0.08114
  Data::Dump: 1.06
  Digest::MD5: 2.36
  Exporter: 5.63
  File::Slurp: 9999.13
  File::Spec: 0
  Lingua::EN::Inflect::Number: 1.1
  Lingua::EN::Inflect::Phrase: 0.02
  List::MoreUtils: 0
  MRO::Compat: 0.09
  Scalar::Util: 0
  Scope::Guard: 0
  Try::Tiny: 0
  namespace::clean: 0
  perl: 5.8.1
resources:
  IRC: irc://irc.perl.org/#dbix-class
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbix-class
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/dbsrgits/DBIx-Class-Schema-Loader.git
version: 0.07002
