---
abstract: 'Dynamic definition of a DBIx::Class::Schema'
author:
  - 'Brandon Black, C<blblack@gmail.com>'
build_requires:
  DBD::SQLite: 1.12
  DBI: 1.56
  File::Path: 0
  IPC::Open3: 0
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Schema-Loader
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan: 0
  Class::Accessor::Fast: 0.30
  Class::C3: 0.18
  Class::Data::Accessor: 0.03
  Class::Inspector: 0
  Class::Unload: 0
  DBIx::Class: 0.07006
  Data::Dump: 1.06
  Digest::MD5: 2.36
  File::Spec: 0
  Lingua::EN::Inflect::Number: 1.1
  Scalar::Util: 0
  Text::Balanced: 0
  UNIVERSAL::require: 0.11
resources:
  license: http://dev.perl.org/licenses/
version: 0.04999_06
